//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcecreamParlourSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordert
    {
        public int ord_id { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<int> cust_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> totprice { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual loginNew loginNew { get; set; }
    }
}
